// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://watwzkalkdpbibbwfpvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhdHd6a2Fsa2RwYmliYndmcHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzMyMDQsImV4cCI6MjA3ODI0OTIwNH0.mwD58CScoQVv9wOE_LFsAlS5hrYv-nkD9BiYmfe44Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});